// REQUEST
export const REQUEST = 'REQUEST';
export const REQUEST_SUCCESS = 'REQUEST_SUCCESS';
export const REQUEST_FAILED = 'REQUEST_FAILED';

// CBR
export const LOAD_CURRENT_CBR_RATES = 'LOAD_CURRENT_CBR_RATES';

// MOEX
export const LOAD_CURRENT_MOEX_INDEXES = 'LOAD_CURRENT_MOEX_INDEXES';

// USER
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

// ACCOUNT
export const FETCH_ACCOUNTS = 'FETCH_ACCOUNTS';
export const FETCH_ACCOUNT_STATES = 'FETCH_ACCOUNT_STATES';
export const SET_ACTIVE_ACCOUNT = 'SET_ACTIVE_ACCOUNT';

// MODAL
export const SHOW_MODAL = 'SHOW_MODAL';
export const CLOSE_MODAL = 'CLOSE_MODAL';
