// REQUEST
export const FETCH_REQUEST = 'FETCH_REQUEST';
export const FETCH_SUCCESS = 'FETCH_SUCCESS';
export const FETCH_FAILED = 'FETCH_FAILED';

// CBR
export const LOAD_CURRENT_CBR_RATES = 'LOAD_CURRENT_CBR_RATES';

// MOEX
export const LOAD_CURRENT_MOEX_INDEXES = 'LOAD_CURRENT_MOEX_INDEXES';

// USER
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

// ACCOUNT
export const LOAD_ACCOUNTS = 'LOAD_ACCOUNTS';
export const SET_ACTIVE_ACCOUNT = 'SET_ACTIVE_ACCOUNT';
