export const FETCH_REQUEST = 'FETCH_REQUEST';
export const FETCH_SUCCESS = 'FETCH_SUCCESS';
export const FETCH_FAILED = 'FETCH_FAILED';

export const LOAD_CURRENT_CBR_RATES = 'LOAD_CURRENT_CBR_RATES';

export const LOAD_CURRENT_MOEX_INDEXES = 'LOAD_CURRENT_MOEX_INDEXES';
